### PR TITLE
Add extra arguments to create certificates

### PR DESCRIPTION
**Pull request by hectorj2f**
I need to check a discovery issue so I might need to verify nothing else is missing.

We are going to simplify the way we deploy g8s but we need to keep this up-to-date.

### CODE REVIEW

**Comment by calvix** [comment]
added functionalite mentioned here: https://github.com/giantswarm/giantswarm/issues/998

**Comment by teemow** [comment]
@calvix it seems you mixed your changes with a commit from @hectorj2f. is this intended?

**Comment by calvix** [comment]
@teemow yes, it made sense to me, since both changes are towards k8s api certs in g8s

**Comment by hectorj2f** [comment]
@calvix I don't mind going ahead with this

**Pull request merged**
