### PR TITLE
DO NOT MERGE: Latest Mayu with old Flatcar for VMWare envs

### PR DESCRIPTION
**Pull request by glitchcrab**
towards https://github.com/giantswarm/giantswarm/issues/17855

this gets us the latest mayu release which allows us to use [hive @v1.9.0](https://github.com/giantswarm/hive/releases/tag/v1.9.0) - this means we can run k8s 1.20.7 on older Flatcar.

this is a fork of https://github.com/giantswarm/mayu/tree/autologin-flag-flatcar with the latest changes from master applied (gets us the `join` function etc).

### CODE REVIEW

**Comment by tfussell** [comment]
Is this going to be a long-lived branch? If so, can we merge it into a minor release branch like `release-v1.1.x` or `release-v1.2.x`? I don't know enough about the history to know which one makes sense.

**Review by tfussell — APPROVED** [review]
Changes make sense, just had a question about the base branch.

**Comment by glitchcrab** [comment]
@tfussell it will be around as long as we are stuck with the older VMWare environments, so an indeterminate length of time. It's difficult to work out when to branch it because it aligns with 1.2.0 but it reverts older changes - i'm open to release version suggestions.

**Comment by glitchcrab** [comment]
closing this in favour of https://github.com/giantswarm/mayu/pull/152

**Pull request closed without merging**
