### PR TITLE
Add support for ignition

### PR DESCRIPTION
**Pull request by hectorj2f**
This PR aims to add support for two bootstrap CoreOS mechanism: ignition and cloudconfig. Obviously, only one mechanism can be used each time.

- [x] A working Ignition installation using `gs_install.yaml`
- [x] Keep both ignition and cloud config configuration mechanism available
- [x] Test that all the systemd units behave as expected with ignition and cloudconfig setup

ping @giantswarm/team-core

### CODE REVIEW

**Comment by hectorj2f** [comment]
ping @teemow

**Comment by hectorj2f** [comment]
ping @teemow

**Comment by teemow** [comment]
@hectorj2f the `mayu-env` file has to be written in both cases:

https://github.com/giantswarm/mayu/blob/add_support_ignition/templates/first_stage_script.sh#L129

**Comment by teemow** [comment]
Otherwise yochu fails:

```
$ sudo systemctl status yochu                                                                                                                                       
● yochu.service - Giant Swarm yochu
   Loaded: loaded (/etc/systemd/system/yochu.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2016-04-08 12:57:22 UTC; 8min ago
  Process: 960 ExecStartPost=/home/core/bin/mayuctl boot-complete --host=10.0.3.251 --port=4080 --no-tls --update-versions (code=exited, status=1/FAILURE)
  Process: 956 ExecStartPost=/bin/sh -c sleep 5 (code=exited, status=0/SUCCESS)
 Main PID: 703 (code=exited, status=0/SUCCESS)

Apr 08 12:57:17 localhost yochu[703]: # call k8s.Teardown()
Apr 08 12:57:17 localhost yochu[703]: call FsClient.Remove(path): /usr/bin/kubectl
Apr 08 12:57:17 localhost yochu[703]: # call k8s.Setup()
Apr 08 12:57:17 localhost yochu[703]: call HTTPClient.Get(endpoint, path): http://10.0.3.251:4080/yochu - k8s/v1.2.2/kubectl
Apr 08 12:57:17 localhost yochu[703]: call FsClient.Write(path, data): /usr/bin/kubectl, <blob:42918024>
Apr 08 12:57:22 localhost mayuctl[960]: 2016/04/08 12:57:22 open /etc/mayu-env: no such file or directory
Apr 08 12:57:22 localhost systemd[1]: yochu.service: Control process exited, code=exited status=1
Apr 08 12:57:22 localhost systemd[1]: Failed to start Giant Swarm yochu.
Apr 08 12:57:22 localhost systemd[1]: yochu.service: Unit entered failed state.
Apr 08 12:57:22 localhost systemd[1]: yochu.service: Failed with result 'exit-code'.
```

**Comment by hectorj2f** [comment]
@teemow I included mayu-env file with the right env variables

**Comment by hectorj2f** [comment]
ping @teemow WFM :yellow_heart:

**Comment by hectorj2f** [comment]
re-ping @teemow  :)

**Comment by teemow** [comment]
WFM too!

**Pull request merged**
