### PR TITLE
Switch to latest ignition

### PR DESCRIPTION
**Pull request by corest**
Towards https://github.com/giantswarm/giantswarm/issues/4085

### CODE REVIEW

**Comment by corest** [comment]
I have an issue with this switch as looks like yaml package is unable to unmarshal nested anonymous structures. 

E.g., in spec `2.2.0` files object had no those anonymous structures: https://github.com/coreos/ignition/blob/master/config/v2_0/types/file.go#L24-L31

Now it looks like this:
https://github.com/coreos/ignition/blob/master/config/v2_2/types/schema.go#L47-L50

And with such schema, yaml package fails to unmarshal data into object. E.g.

```
package main

import (
	"encoding/json"
	"fmt"
	"gopkg.in/yaml.v2"
)

type Test struct {
	Test1
	Test2
}

type Test1 struct {
	F1 int
	F2 int
}

type Test2 struct {
	F3 int
	F4 int
}

func main() {
	yaml_obj := []byte(`f1: 1
f2:2
f3:3
f4:4
`)

	json_obj := []byte(`{
"f1":1,
"f2":2,
"f3":3,
"f4":4
}
`)
	yaml_cfg := Test{}
	json_cfg := Test{}

	yaml.Unmarshal(yaml_obj, &yaml_cfg)
	json.Unmarshal(json_obj, &json_cfg)

	fmt.Println(yaml_cfg)
	fmt.Println(json_cfg)

}
```

gives output

```
{{0 0} {0 0}}
{{1 2} {3 4}}
```

**Comment by xh3b4sd** [comment]
It would be good to comment on the code lines which suffer from the mentioned problems. As a workaround, what about doing the codec dance twice and use JSON first so you get a decent structure and then you go into YAML based on the JSON just to make it work. Further we should maybe create an upstream issue in the yaml repo or in the CoreOS repo. Or both, whatever is appropriate.

**Comment by corest** [comment]
Here is the place I lose all my config files 
https://github.com/giantswarm/mayu/blob/c5e7e7fc9f643302b2f893b43973d0a054fb2587/pxemgr/ignition.go#L111
as they become initialized with empty structures

**Comment by xh3b4sd** [comment]
You could define the structures on your own here and use them for marshalling.

**Comment by corest** [comment]
As @xh3b4sd suggested, I copied ignition structure and rewrote it without embedded nested structures. Works fine and taking into account ignition spec update happens once in a ~2 years, we should be good.

**Comment by corest** [comment]
Anyway, this is blocked for now by `1575.5.0` coreos version, which still has ignition `0.19.0` with spec `2.0.0`

**Comment by xh3b4sd** [comment]
Towards reliability and releng concerns there should be some kind of automated tests though so we can be sure that in case some definition changes upstream for some reasons we catch it before we deploy something that is inherently broken. /cc @giantswarm/sig-releng

**Comment by corest** [comment]
We are not syncing with upstream automatically. Also, there is ignition version and spec version. And while ignition changes more often, spec for schema doesn't change for ~5 versions. So, there is no risk something can break on its own.

**Comment by xh3b4sd** [comment]
Ok, so how do I have to check that everything is fine when I go and update the spec? AFAIK this is manual right? So I think there should be some efforts to automatically verify functionality. Like, writing tests. I just wanted to mention that.

**Comment by corest** [comment]
Ignition itself is located in the `hive` repo, so if it worth to check schema - it should be done in the hive repo CI

**Comment by corest** [comment]
There is a test for schema, which failed after spec version was updated. So it did the job. Of course, we can extend it with additional structures

**Comment by corest** [comment]
Closed in favor of https://github.com/giantswarm/mayu/pull/133

**Pull request closed without merging**
