### PR TITLE
updated vendor deps

### PR DESCRIPTION
**Pull request by xh3b4sd**
This PR fixes the vendor issues we saw recently. Some package had been treated as git submodule. No idea why that was. I removed the vendor dir and the glide files and initialized the glide project again and reinstalled all dependencies. The go package causing the trouble seems to be tracked like all the other deps by git now. So we should be good again.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
@calvix the build basically works. There are only tests failing. Is this because I updated deps or was this caused by your recent changes on the config commands? You want to take over here? I actually only wanted to help out with the vendoring part. <3

**Comment by calvix** [comment]
@xh3b4sd thanks i will take over

**Comment by calvix** [comment]
Hehe so i have no idea why test fails, because the outputs are completely same and i dont get any fails when i run 
```
#: go test -v $(glide novendor | grep -v infopusher)
=== RUN   Test_Client_001
--- PASS: Test_Client_001 (0.00s)
=== RUN   Test_Client_002
--- PASS: Test_Client_002 (0.00s)
=== RUN   Test_Client_003
--- PASS: Test_Client_003 (0.00s)
=== RUN   Test_Client_004
--- PASS: Test_Client_004 (0.00s)
=== RUN   Test_Client_005
--- PASS: Test_Client_005 (0.00s)
=== RUN   Test_Client_006
--- PASS: Test_Client_006 (0.00s)
=== RUN   Test_Client_007
--- PASS: Test_Client_007 (0.00s)
=== RUN   Test_Client_008
--- PASS: Test_Client_008 (0.00s)
=== RUN   Test_Client_009
--- PASS: Test_Client_009 (0.00s)
=== RUN   Test_Client_010
--- PASS: Test_Client_010 (0.00s)
=== RUN   Test_Client_011
--- PASS: Test_Client_011 (0.00s)
=== RUN   Test_Client_012
--- PASS: Test_Client_012 (0.00s)
=== RUN   Test_Client_013
--- PASS: Test_Client_013 (0.00s)
=== RUN   Test_Client_014
--- PASS: Test_Client_014 (0.00s)
=== RUN   Test_Client_015
--- PASS: Test_Client_015 (0.00s)
=== RUN   Test_Client_016
--- PASS: Test_Client_016 (0.00s)
=== RUN   Test_Client_017
--- PASS: Test_Client_017 (0.00s)
=== RUN   Test_Client_018
--- PASS: Test_Client_018 (0.00s)
PASS
ok  	github.com/giantswarm/mayu/client	0.010s
?   	github.com/giantswarm/mayu/fs	[no test files]
?   	github.com/giantswarm/mayu/hostmgr	[no test files]
?   	github.com/giantswarm/mayu/httputil	[no test files]
?   	github.com/giantswarm/mayu/logging	[no test files]
?   	github.com/giantswarm/mayu/mayuctl	[no test files]
=== RUN   Test_IPUtil_IncIP
--- PASS: Test_IPUtil_IncIP (0.00s)
=== RUN   Test_IPUtil_IPLessThanOrEqual
--- PASS: Test_IPUtil_IPLessThanOrEqual (0.00s)
PASS
ok  	github.com/giantswarm/mayu/pxemgr	0.006s
?   	github.com/giantswarm/mayu/error	[no test files]
=== RUN   TestHTTPSCertConfigValidation
--- PASS: TestHTTPSCertConfigValidation (0.00s)
=== RUN   TestHTTPCertConfigFileStatValidation
--- PASS: TestHTTPCertConfigFileStatValidation (0.00s)
PASS
ok  	github.com/giantswarm/mayu	0.006s

```

**Comment by calvix** [comment]
ok iam going to dig deeper later

**Comment by xh3b4sd** [comment]
@calvix I fixed the tests. I am actually wondering how these tests could have ever worked, since it looks like the condition which checks the actual and the expected output was just wrong. Please have a look. When it is good then lets merge and the builds in your other PRs should be good as well when you merge the master in.

**Comment by calvix** [comment]
wow i mean yeah that totaly make sense,  this is some deep magic, anyway thanks

**Pull request merged**
